{
 "title": "nccostorage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Live Buckets",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "live_buckets" }
   ]
  },
  {
   "title": "Update Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(update_time_sum[5m]))/sum(rate(update_time_count[5m]))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(update_time_bucket[5m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(update_time_bucket[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(update_time_bucket[5m])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(update_time_bucket[5m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Update Errors Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(update_error[5m])) / sum(rate(update_count[5m]))) * 100",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Update Errors Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "increase(update_error[1m])" }
   ]
  },
  {
   "title": "Live NCCOs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "live_nccos" }
   ]
  }
 ]
}