version: '3'
services:
  prometheus:
    build: './prometheus'
    ports:
      - '9090:9090'
  graphana:
    build: './grafana'
    ports:
      - '3000:3000'
  nccostorage:
    build: '../'
    ports:
      - '8080:8080'
