global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'nccostorage'
    static_configs:
      - targets: ['nccostorage:8080']
